name: PR Review Environment

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: read

jobs:
  deploy:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate deterministic tag
        id: randtag
        run: echo "tag=pr-${{ github.event.number }}-$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-12)" >> $GITHUB_OUTPUT

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: signalen/backend:${{ steps.randtag.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy with webhook
        run: |
          curl -X POST ${{ SEMAPHORE_WEBHOOK_URL }} \
          -H "Authorization: Bearer ${{ SEMAPHORE_WEBHOOK_TOKEN }}" \
          -d '{"from_pipeline": "true", "municipality_dnsname": "review-${{ steps.randtag.outputs.tag }}.review-scw.delta10-review.nl", "signalen_bucket_name": "signalen-review", "signalen_backend_tag": "${{ steps.randtag.outputs.tag }}" }'

      # Output preview URL
      - name: Output preview URL
        run: |
          echo "Preview: https://meldingen.review-${{ steps.randtag.outputs.tag }}.review-scw.delta10-review.nl"
